# Generated by Django 3.2 on 2021-05-21 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='complaint_category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(blank=True, default=None, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='complaint_subcategory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('subcategory', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('priority', models.SmallIntegerField(blank=True, default=1, null=True)),
                ('complaint_cat', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='complaint.complaint_category')),
            ],
        ),
        migrations.CreateModel(
            name='complaint_user',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(default=None, max_length=250)),
                ('complaint_info', models.TextField(blank=True, default=None, null=True)),
                ('email', models.CharField(default=None, max_length=250)),
                ('address', models.CharField(default=None, max_length=5000)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('alternative_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('aadhar_no', models.CharField(default=None, max_length=15, unique=True)),
                ('pincode', models.IntegerField(default=None)),
                ('city', models.CharField(default=None, max_length=50)),
                ('state', models.CharField(default=None, max_length=50)),
                ('complaint_aadhar', models.ImageField(upload_to='complaint_aadhar')),
                ('complaint_spotimage', models.ImageField(upload_to='complaint_spotimage')),
                ('complaint_cat', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='complaint.complaint_category')),
                ('complaint_subcat', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='complaint.complaint_subcategory')),
            ],
        ),
    ]
