# Generated by Django 3.2 on 2021-05-29 10:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('complaint', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint_user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='complaint_user',
            name='is_opt_verify',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='complaint_user',
            name='otp_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='complaint_user',
            name='otp_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
