# Generated by Django 3.2 on 2021-05-30 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaint', '0003_alter_complaint_user_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint_user',
            name='aadhar_no',
            field=models.CharField(default=None, max_length=15),
        ),
    ]
