# Generated by Django 3.2 on 2021-05-30 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('complaint', '0004_alter_complaint_user_aadhar_no'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complaint_user',
            old_name='is_opt_verify',
            new_name='is_otp_verify',
        ),
    ]
