# Generated by Django 3.2 on 2021-06-05 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaint', '0005_rename_is_opt_verify_complaint_user_is_otp_verify'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint_user',
            name='complaint_aadhar',
            field=models.ImageField(upload_to='media/complaint_aadhar'),
        ),
        migrations.AlterField(
            model_name='complaint_user',
            name='complaint_spotimage',
            field=models.ImageField(upload_to='media/complaint_spotimage'),
        ),
    ]
