# Generated by Django 3.2 on 2021-06-07 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaint', '0006_auto_20210605_1912'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint_subcategory',
            name='servant_role',
            field=models.SmallIntegerField(blank=True, default=1, null=True),
        ),
    ]
