# Generated by Django 3.2 on 2021-06-15 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaint', '0012_complaint_user_progress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint_user',
            name='progress',
            field=models.IntegerField(default=25),
        ),
    ]
