# Generated by Django 3.2 on 2021-06-16 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaint', '0013_alter_complaint_user_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint_user',
            name='abort_reason',
            field=models.CharField(blank=True, default='No reason', max_length=600, null=True),
        ),
    ]
