# Generated by Django 3.2 on 2021-06-14 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servant', '0006_alter_users_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='user_role',
            field=models.SmallIntegerField(choices=[(1, 'MSEB Chief Engineer'), (2, 'Health Department'), (3, 'Water Conservation officer'), (4, 'Municipal corporation'), (5, 'Department Safety Officer')], default=0),
        ),
    ]
